# Site wide configuration

title: 
Oh, the comfort —
the inexpressible comfort of feeling safe with a person —
having neither to weigh thoughts nor measure words,
but pouring them all right out,
just as they are,
chaff and grain together;
certain that a faithful hand will take and sift them,
keep what is worth keeping,
and then with the breath of kindness blow the rest away.
from A Life for a Life by Dinah Maria Mulock Craik 1859

locale: en_US
description: Gina Edwards, Ph.D., N.C.C.
logo: logo.png
url: http://ginaedwardsphd.com

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

comments: false

# Site owner
owner:
  name: Gina Edwards
  avatar: logo.png
